version: '3.8'

services:
  service:
    build:
      context: ./service
    environment:
      - SERVICE_PORT=${SERVICE_PORT}
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    container_name: ks-service
    volumes:
      - type: bind
        source: ks-source
        target: /source

volumes:
  ks-source:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../