// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: api/proto/keeperserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_LOGIN_PASSWORD SecretType = 0
	SecretType_CREDIT_CARD    SecretType = 1
	SecretType_TEXT           SecretType = 2
	SecretType_MEDIA          SecretType = 3
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "LOGIN_PASSWORD",
		1: "CREDIT_CARD",
		2: "TEXT",
		3: "MEDIA",
	}
	SecretType_value = map[string]int32{
		"LOGIN_PASSWORD": 0,
		"CREDIT_CARD":    1,
		"TEXT":           2,
		"MEDIA":          3,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_keeperserver_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_api_proto_keeperserver_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_keeperserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeperserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_keeperserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeperserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *PingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserCredentialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserCredentialsRequest) Reset() {
	*x = UserCredentialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_keeperserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCredentialsRequest) ProtoMessage() {}

func (x *UserCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeperserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCredentialsRequest.ProtoReflect.Descriptor instead.
func (*UserCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{2}
}

func (x *UserCredentialsRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserCredentialsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UserCredentialsResponse) Reset() {
	*x = UserCredentialsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_keeperserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCredentialsResponse) ProtoMessage() {}

func (x *UserCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeperserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCredentialsResponse.ProtoReflect.Descriptor instead.
func (*UserCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{3}
}

func (x *UserCredentialsResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserCredentialsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UploadPlainSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UploadPlainSecretRequest) Reset() {
	*x = UploadPlainSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_keeperserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPlainSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPlainSecretRequest) ProtoMessage() {}

func (x *UploadPlainSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeperserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPlainSecretRequest.ProtoReflect.Descriptor instead.
func (*UploadPlainSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{4}
}

func (x *UploadPlainSecretRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *UploadPlainSecretRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UploadPlainSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UploadPlainSecretResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UploadPlainSecretResponse) Reset() {
	*x = UploadPlainSecretResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_keeperserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPlainSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPlainSecretResponse) ProtoMessage() {}

func (x *UploadPlainSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeperserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPlainSecretResponse.ProtoReflect.Descriptor instead.
func (*UploadPlainSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{5}
}

func (x *UploadPlainSecretResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MediaSecretMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MediaSecretMetadata) Reset() {
	*x = MediaSecretMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_keeperserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaSecretMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSecretMetadata) ProtoMessage() {}

func (x *MediaSecretMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeperserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSecretMetadata.ProtoReflect.Descriptor instead.
func (*MediaSecretMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{6}
}

func (x *MediaSecretMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MediaSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *MediaSecret) Reset() {
	*x = MediaSecret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_keeperserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSecret) ProtoMessage() {}

func (x *MediaSecret) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeperserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSecret.ProtoReflect.Descriptor instead.
func (*MediaSecret) Descriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{7}
}

func (x *MediaSecret) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type UploadMediaSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*UploadMediaSecretRequest_Metadata
	//	*UploadMediaSecretRequest_Data
	Request isUploadMediaSecretRequest_Request `protobuf_oneof:"request"`
}

func (x *UploadMediaSecretRequest) Reset() {
	*x = UploadMediaSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_keeperserver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMediaSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaSecretRequest) ProtoMessage() {}

func (x *UploadMediaSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeperserver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaSecretRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{8}
}

func (m *UploadMediaSecretRequest) GetRequest() isUploadMediaSecretRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *UploadMediaSecretRequest) GetMetadata() *MediaSecretMetadata {
	if x, ok := x.GetRequest().(*UploadMediaSecretRequest_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (x *UploadMediaSecretRequest) GetData() *MediaSecret {
	if x, ok := x.GetRequest().(*UploadMediaSecretRequest_Data); ok {
		return x.Data
	}
	return nil
}

type isUploadMediaSecretRequest_Request interface {
	isUploadMediaSecretRequest_Request()
}

type UploadMediaSecretRequest_Metadata struct {
	Metadata *MediaSecretMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadMediaSecretRequest_Data struct {
	Data *MediaSecret `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadMediaSecretRequest_Metadata) isUploadMediaSecretRequest_Request() {}

func (*UploadMediaSecretRequest_Data) isUploadMediaSecretRequest_Request() {}

type UploadMediaSecretResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UploadMediaSecretResponse) Reset() {
	*x = UploadMediaSecretResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_keeperserver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMediaSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaSecretResponse) ProtoMessage() {}

func (x *UploadMediaSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_keeperserver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaSecretResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_keeperserver_proto_rawDescGZIP(), []int{9}
}

func (x *UploadMediaSecretResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UploadMediaSecretResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadMediaSecretResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_keeperserver_proto protoreflect.FileDescriptor

var file_api_proto_keeperserver_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x22, 0x27, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3c, 0x0a, 0x0c, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4a, 0x0a, 0x16, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x45, 0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5a, 0x0a, 0x18,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x19, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x29, 0x0a, 0x13, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0b, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0xa3, 0x01, 0x0a, 0x18,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x59, 0x0a, 0x19, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x46, 0x0a, 0x0a,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x4f,
	0x47, 0x49, 0x4e, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x43, 0x52, 0x45, 0x44, 0x49, 0x54, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x45, 0x44,
	0x49, 0x41, 0x10, 0x03, 0x32, 0x95, 0x03, 0x0a, 0x0d, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1f,
	0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x63, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x2a, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x2a, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x2c, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x29, 0x5a, 0x27,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x73, 0x73, 0x61,
	0x69, 0x31, 0x2f, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_keeperserver_proto_rawDescOnce sync.Once
	file_api_proto_keeperserver_proto_rawDescData = file_api_proto_keeperserver_proto_rawDesc
)

func file_api_proto_keeperserver_proto_rawDescGZIP() []byte {
	file_api_proto_keeperserver_proto_rawDescOnce.Do(func() {
		file_api_proto_keeperserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_keeperserver_proto_rawDescData)
	})
	return file_api_proto_keeperserver_proto_rawDescData
}

var file_api_proto_keeperserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_keeperserver_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_keeperserver_proto_goTypes = []interface{}{
	(SecretType)(0),                   // 0: keeperservice.grpc.SecretType
	(*PingRequest)(nil),               // 1: keeperservice.grpc.PingRequest
	(*PingResponse)(nil),              // 2: keeperservice.grpc.PingResponse
	(*UserCredentialsRequest)(nil),    // 3: keeperservice.grpc.UserCredentialsRequest
	(*UserCredentialsResponse)(nil),   // 4: keeperservice.grpc.UserCredentialsResponse
	(*UploadPlainSecretRequest)(nil),  // 5: keeperservice.grpc.UploadPlainSecretRequest
	(*UploadPlainSecretResponse)(nil), // 6: keeperservice.grpc.UploadPlainSecretResponse
	(*MediaSecretMetadata)(nil),       // 7: keeperservice.grpc.MediaSecretMetadata
	(*MediaSecret)(nil),               // 8: keeperservice.grpc.MediaSecret
	(*UploadMediaSecretRequest)(nil),  // 9: keeperservice.grpc.UploadMediaSecretRequest
	(*UploadMediaSecretResponse)(nil), // 10: keeperservice.grpc.UploadMediaSecretResponse
}
var file_api_proto_keeperserver_proto_depIdxs = []int32{
	7,  // 0: keeperservice.grpc.UploadMediaSecretRequest.metadata:type_name -> keeperservice.grpc.MediaSecretMetadata
	8,  // 1: keeperservice.grpc.UploadMediaSecretRequest.data:type_name -> keeperservice.grpc.MediaSecret
	1,  // 2: keeperservice.grpc.KeeperService.Ping:input_type -> keeperservice.grpc.PingRequest
	3,  // 3: keeperservice.grpc.KeeperService.Register:input_type -> keeperservice.grpc.UserCredentialsRequest
	3,  // 4: keeperservice.grpc.KeeperService.Login:input_type -> keeperservice.grpc.UserCredentialsRequest
	9,  // 5: keeperservice.grpc.KeeperService.UploadMediaSecret:input_type -> keeperservice.grpc.UploadMediaSecretRequest
	2,  // 6: keeperservice.grpc.KeeperService.Ping:output_type -> keeperservice.grpc.PingResponse
	4,  // 7: keeperservice.grpc.KeeperService.Register:output_type -> keeperservice.grpc.UserCredentialsResponse
	4,  // 8: keeperservice.grpc.KeeperService.Login:output_type -> keeperservice.grpc.UserCredentialsResponse
	10, // 9: keeperservice.grpc.KeeperService.UploadMediaSecret:output_type -> keeperservice.grpc.UploadMediaSecretResponse
	6,  // [6:10] is the sub-list for method output_type
	2,  // [2:6] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_keeperserver_proto_init() }
func file_api_proto_keeperserver_proto_init() {
	if File_api_proto_keeperserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_keeperserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_keeperserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_keeperserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCredentialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_keeperserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCredentialsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_keeperserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPlainSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_keeperserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPlainSecretResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_keeperserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaSecretMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_keeperserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaSecret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_keeperserver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMediaSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_keeperserver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMediaSecretResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_keeperserver_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*UploadMediaSecretRequest_Metadata)(nil),
		(*UploadMediaSecretRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_keeperserver_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_keeperserver_proto_goTypes,
		DependencyIndexes: file_api_proto_keeperserver_proto_depIdxs,
		EnumInfos:         file_api_proto_keeperserver_proto_enumTypes,
		MessageInfos:      file_api_proto_keeperserver_proto_msgTypes,
	}.Build()
	File_api_proto_keeperserver_proto = out.File
	file_api_proto_keeperserver_proto_rawDesc = nil
	file_api_proto_keeperserver_proto_goTypes = nil
	file_api_proto_keeperserver_proto_depIdxs = nil
}
